namespace: Radius.Core
location:
  global: "http://localhost:8080"
types:
  applications:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  containers:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  environments:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  extenders:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  gateways:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  recipePacks:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  secretStores:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  volumes:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
