namespace: Radius.Data
location:
  global:
    "http://localhost:8080"
types:
  sqlDatabases:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  mongoDatabases:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  redisCaches:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  rabbitMQQueues:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
