namespace: Radius.Compute
location:
  global:
    "http://localhost:8080"
types:
  containers:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
  gateways:
    apiVersions:
      "2025-08-01-preview":
        schema: {}
